version: '3.8'

services:
  iris-messenger:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/iris-messenger
      - /iris-messenger/node_modules
    ports:
      - 5173:5173
